name: Synchronize Labels
on:
  push:
    branches:
    - main
    - v2
    paths:
    - .github/labels.yml

jobs:
  synchronize:
    name: Synchronize Labels
    runs-on:
    - ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: micnncim/action-label-syncer@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
